DEBUG = True

SQLALCHEMY_DATABASE_NAME = "ccmap.db"
SQLALCHEMY_TRACK_MODIFICATIONS = False
DATABASE_CONNECT_OPTIONS = {}

SECRET_KEY = "dev"

GOOGLEMAPS_KEY = "<GOOGLEMAPS_API>"
#GOOGLE_ANALYTICS_KEY = "<GOOGLE_ANALYTICS_KEY>"
